

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="public/styles.css"/>
    <script src="/js/jquery.min.js">
    </script>
    <script>
        $(document).ready(function()
        {
            i=0;
            while (i<=2){
                $("#p1").css("color","cyan").slideDown(3000).slideUp(3000);
                i++;
            }

        });

    </script>
</head>
<body>
<img src="<?php echo$this->baseUrl('/images/tron.jpg')?>" class="backImage" >
<p id="p1" style="z-index: 1;position:absolute;margin-top: 270px;margin-left: 600px;font-size:50px "> <?php echo $this->logo ?></p>


</body>
</html>