
<H3 style="color:cyan"> <?php echo ($this->activated)? "Your account has been activated! Autologin in a few seconds...":"Wrong activation email. Account not activated!" ;?></H3>

<script type="text/javascript">

    var baseUrl = "<?php echo rtrim($this->baseUrl('/'),'/')?>";
    setTimeout(function(){ location.href =baseUrl+"/auth/silent?username=<?php echo $this->username?>&password=<?php echo $this->password ?>"},5000)


</script>

