
<div>
    <img src="/images/tron.jpg" class="backImage" >
<div id="idLogin" style="width: 350px; position: static; margin: 200px 400px; border: 2px solid; padding: 10px; border-radius: 5px; border-color: cyan ">
    <form action="/auth/silent" id="jsAuth" method="post" role="form" style="color:#2aabd2">
        <div class="form-group">
            <label for="InputEmail">Username or Email address</label>
            <input type="text" class="form-control required" id="InputEmail" name="username" placeholder="Username/Email">
        </div>
        <div class="form-group">
            <label for="InputPassword">Password</label>
            <input type="password" class="form-control" id="InputPassword" name="password" placeholder="Password">
        </div>

        <div class="buttonGroup">
            <button type="submit" class="btn btn-success">Sign in</button>
        </div>
    </form>
    <br>
    <div class="buttonGroup">
        <span style="color: #0398CA">Not registered? </span>
        <a href="<?php echo $this->baseUrl('/auth/signup')?>" class="btn btn-warning">Sign up</a>
    </div>
    <div class="clearfix"></div>
</div>
</div>

<script type="text/javascript">

    $(function(){
        $('#jsAuth').validate({

            messages: {
                username:{
                    required: "please enter your username/email"
                }

            }
        });
    })
</script>