<?php
if  (! is_null($this->emailto))
    $phrase="email address ".$this->emailto."<BR>Please check that email to activate the account!</H3>";
else
    $phrase="your email address.<BR>Please check your email to activate your account!</H3>";


?>

<H3 style="color: cyan">An email containing a registration confirmation has been sent to <?php echo $phrase ?></H3>


<script type="text/javascript">


 //  setTimeout(function(){ location.href ="<?php echo $this->goto ?>"},5000)


</script>