<!-- from AnyUserController->photosAction-->

<?php
$this->headScript()->appendFile($this->baseUrl('/js/jquery.validate.min.js'))
    ->appendFile($this->baseUrl('/js/dropzone.js'))
    ->appendFile($this->baseUrl('/js/upload-photo.js'))
    ->appendFile($this->baseUrl('/js/underscore-master/underscore.js'))
    ->appendFile($this->baseUrl('/js/underscore-master/underscore-min.js'));

$photopath = $_SERVER["DOCUMENT_ROOT"].('/photos/gallery/original');


$picturesFiles = glob ( $photopath."/".sprintf("p%06d%s",$this->identity["id"],"*.*"));

$pictures = array();
for( $i = 0; $i < count($picturesFiles); $i++ ){
    $pictures[] = pathinfo( $picturesFiles[$i],PATHINFO_BASENAME );
}

My_Log_Me::Log($picturesFiles);
?>

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="styles.css"/>

</head>

<body>
<div class="row user-page" style="background-color: #ffffff">
<?php
    echo $this->partial('_partials/user-menu.phtml',
    array(
        'identity' => $this->identity,
        'action' => $this->action
    ));

    ?>

    <div class="col-md-9" style="position: relative;top:5px;">
        <div >
        <img src="/images/upload-photos.jpg" style="position: relative; top: 15px; float: right; height: 60px; cursor: pointer;" onclick="showDroparea()">
        </div>
       <h3 class="title">Gallery</h3>


        <div id="album"  style="position:relative;overflow-y:scroll;height:700px;width:850px;display: block">


            <?php for( $i = 0; $i < count( $pictures ); $i++ ): ?>
                <div style="border: 3px solid red;float: left;margin: 5px;">
                <img width="260px" src="<?php echo $this->baseUrl('/photos/gallery/original') . "/". $pictures[$i]?>" alt="<?php echo $photopath ."/". $pictures[$i]?>" >
                </div>
            <?php endfor ?>


        </div>
    </div>

    <div class="myDropzone " style="display:none; overflow-y:scroll; width: 850px; height: 700px;position: absolute;z-index: 3000;background-color: #ffffff;"  id="droparea" title="Click or drag here to add picture" >
    <div style="float: right;position: relative; top: -20px">
        <button id="resetbutton" class="btn btn-danger" style="position:relative;float: right">Reset</button>
        <button id="uploadbutton" class="btn btn-primary" style="position:relative;float: right; margin-right: 10px" >Upload photos</button>

    </div>
    <div id="uploadarea" style="margin-top: 40px">
    <form action="<?php echo $this->baseUrl('/upload/photo') ?>" class="dropzone" id="my-dropzone">
        <input type="hidden" id="realfiles" name="realfiles">
    </form>
    </div>
      <div id="uploaddone" style="display: none;background-color: greenyellow; text-align:center;border-radius: 40%;font-size: 10px;padding: 20px" >
      </div>
    </div>

</div>


</body>
</html>

<script type="text/javascript">

var position = $("#album").offset();
var dropArea = $("#droparea");

dropArea.css(position);


function showDroparea(){

    dropArea.slideToggle(function(){
        if( ! dropArea.is(':visible') ){
            location.reload(true);
        }
    });

}



</script>
