<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="favicon.png">

    <title>Jumbotron Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/styles.css" rel="stylesheet">
    <script src="//code.jquery.com/jquery-1.10.2.min.js"></script>

</head>

<body>

<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Project T-App</a>
        </div>

        <?php echo $this->placeholder('signinbar') ?>

<!--        bara de inregistrare
        <div class="navbar-collapse collapse">

                <div class="form-group">
                    <input type="text" name="username" placeholder="Email" class="form-control">
                </div>
                <div class="form-group">
                    <input type="password" name=""password" placeholder="Password" class="form-control">
                </div>
                <button type="submit" class="btn btn-success">Sign in</button>

        </div><!--/.navbar-collapse -->
    </div>
</div>

<div class="container">

    <?php echo $this->layout()->content; ?>


    <footer>
        <p>&copy; Company 2013</p>
    </footer>
</div> <!-- /container -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->

<script src="/js/bootstrap.min.js"></script>
<script src="/js/jquery.js"></script>
<script src="/js/jquery-cookie.js"></script>
<?php print $this->headScript() ?>

</body>
</html>
