<?php
$this->headScript()->appendFile($this->baseUrl('/js/jquery.validate.min.js'));
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="favicon.png">

    <title>TAplication</title>

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/styles.css" rel="stylesheet">
    <link href="/dropzone.css" rel="stylesheet">
    <script src="//code.jquery.com/jquery-1.10.2.min.js"></script>

</head>
<body>
<img src="/images/tron.jpg" class="backImage" >
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Project T-App</a>
        </div>
        <?php  $identity = Zend_Auth::getInstance()->getIdentity();?>

        <?php if( Zend_Auth::getInstance()->hasIdentity() ): ?>
            <form action="/auth/logout" method="post" class="navbar-form navbar-right"  role="form">

                  <DIV style="float: left"> <H4 class="badge navbar-right" style="color: greenyellow;background-color: royalblue;font-size: 17px"><?php echo "Welcome ".$identity["first_name"]." ".$identity["last_name"] ?></H4></DIV>

                <button type="submit" class="btn btn-success" style="position:relative;left:10px;top: 3px  " >LogOut</button>
            </form>
        <?php else: ?>
            <div >
            <form class="navbar-form navbar-right" role="form">
              <span style="left: -12px; top: 4px; position: relative; color: #ffffff">OR</span>
               <a href = "<?php echo $this->baseurl("/auth/signup") ?>"> <button type="button" class="btn btn-warning" style="padding: 6px">Sign up</button></a>

            </form>
            <form action="/auth/silent" method="post" id="jsAuthUser" class="navbar-form navbar-right"   role="form">
                <div class="form-group">
                    <input type="text" name="username" placeholder="Username/Email" class="form-control required">
                </div>
                <div class="form-group">
                    <input type="password" name="password" placeholder="Password" class="form-control ">
                </div>

                <button type="submit" class="btn btn-success">Sign in</button>
            </form>

        </div>
        <?php endif ?>

    </div>
</div>


<div class="container" >

    <?php echo $this->layout()->content; ?>


<!--    <footer>
        <p>&copy; Company 2013</p>
    </footer>-->
</div> <!-- /container -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->

<script src="/js/jquery-1.11.0.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
<script src="/js/jquery-cookie.js"></script>
<?php echo $this->headScript() ?>
<script type="text/javascript">

    $(function(){
        $('#jsAuthUser').validate({

            messages: {
                username:{
                    required: ""
                }

            }
        });
    })
</script>

</body>
</html>
