<!--left sidebar for users-->
<div class="col-md-3 m-menu" >
    <h3><?php echo $this->identity['full_name'] ?></h3>
    <ul class="nav nav-pills nav-stacked">
        <li <?php echo $this->action == 'edit' ? 'class="active"':''?>>
            <a href="<?php echo $this->baseUrl('/any-user/edit').'?id='. $this->identity['id'] ?>">Profile</a>
        </li>
        <li <?php echo $this->action == 'photos' ? 'class="active"':''?>>
            <a href="<?php echo $this->baseUrl('/any-user/photos')?>">Photos</a>
        </li>
        <li <?php echo $this->action == 'gallery' ? 'class="active"':''?>>
            <a href="<?php echo $this->baseUrl('/upload/gallery')?>">Gallery</a>
        </li>
    </ul>
</div>
