<!-- from AnyUserController->photosAction or from UserController->photoAction pass to UplloadController->photoAction-->

<?php
$this->headScript()->appendFile($this->baseUrl('/js/jquery.validate.min.js'))
    ->appendFile($this->baseUrl('/js/dropzone.js'))
    ->appendFile($this->baseUrl('/js/upload-photo.js'));

$photopath = $_SERVER["DOCUMENT_ROOT"].('/photos/gallery/thumb');


$picturesFiles = glob ( $photopath."/".sprintf("p%06d%s",$this->identity["id"],"*.*"));

$pictures = array();
for( $i = 0; $i < count($picturesFiles); $i++ ){
    $pictures[] = pathinfo( $picturesFiles[$i],PATHINFO_BASENAME );
}


?>

<!DOCTYPE html>

<head>
    <link rel="stylesheet" type="text/css" href="styles.css"/>

</head>

<body>
<div class="row user-page" style="background-color: #ffffff">
<?php
require_once("sidebar.php");
?>

    <div id="container" class="col-md-9" style="position: relative; top:5px;">
        <div>
            <img src="/images/upload-photos.jpg" style="top: 15px; float: right; height: 60px; cursor: pointer;" onclick="showDroparea()" title="click to extend/minimize upload area">
        </div>

        <h3 class="title">Gallery</h3>

        <form id="deletephotos" action="<?php echo $this->baseUrl('/upload/delete-from-album') ?>">
            <button class="btn btn-danger" style="margin-bottom: 20px;position: relative;top:5px" title="Mark photos first for deletion" onclick="document.getElementById('deletephotos').submit()">Delete photos</button>
            <input type="hidden" id="photostodelete" name="photostodelete">

        <div id="album" style="overflow-y:scroll;height:650px;width:850px;display: block">

            <?php for( $i = 0; $i < count( $pictures ); $i++ ): ?>
                <div class="photoFrame">

                    <img id="<?php echo $pictures[$i] ?>"
                         src="<?php echo $this->baseUrl('/photos/gallery/thumb') . "/". $pictures[$i]?>"
                         alt="<?php echo $photopath ."/". $pictures[$i]?>" onclick="mark(this,<?php echo $i ?>)" >

                </div>
            <?php endfor ?>

        </div>
       </form>


        <div class="myDropzone" id="dropareaphoto"  title="Click or drag here to add picture" >
            <div class="ta-right">
                <button id="closeButton" class="btn btn-danger" >Close</button>
                <button id="resetbutton" class="btn btn-danger" >Reset</button>
                <button id="uploadbutton" class="btn btn-primary">Upload photos</button>
            </div>

            <div id="uploadarea" >
                <form action="<?php echo $this->baseUrl('/upload/photo') ?>" class="dropzone" id="my-dropzone">
                    <input type="hidden" id="realfiles" name="realfiles">
                </form>
            </div>
            <div id="uploaddone"
                 style="display: none;background-color: greenyellow; text-align:center;border-radius: 40%;font-size: 10px;padding: 20px" >
            </div>
        </div>

    </div>

</div>


</body>


<script type="text/javascript">

var dropArea = $("#dropareaphoto");

var photos=[];
var photolist=[];

function showDroparea(){

    dropArea.slideToggle(function(){
        if( ! dropArea.is(':visible') ){
             location.reload(true);
        }

    });

}

function mark(elem,i){
    if (photos[i]==null)
        photos[i]=0;

    if (photos[i]==0)
    {
        elem.style.opacity = "0.6";
        elem.style.filter  = 'alpha(opacity=60)';
        photos[i]=1;  //marked for delete
        photolist.push(elem.id);
    }
    else
    {
        elem.style.opacity = "1";
        elem.style.filter  = 'alpha(opacity=100)';
        photos[i]=0;
        photolist.splice(elem.id,1);
    }
    $("#photostodelete").val(JSON.stringify(photolist));

}



</script>
