<!-- from AnyUserController->photosAction or from UserController->photoAction pass to UplloadController->photoAction-->

<?php
$this->headScript()->appendFile($this->baseUrl('/js/jquery.validate.min.js'))
    ->appendFile($this->baseUrl('/js/dropzone.js'))
    ->appendFile($this->baseUrl('/js/upload-photo.js'));

$photopath = PUBLIC_PATH.('/photos/gallery/thumb');


$picturesFiles = glob ( $photopath."/".sprintf("p%06d%s",$this->identity["id"],"*.*"));

$pictures = array();
for( $i = 0; $i < count($picturesFiles); $i++ ){
    $pictures[] = pathinfo( $picturesFiles[$i],PATHINFO_BASENAME );
}


?>

<!DOCTYPE html>

<head>
    <link rel="stylesheet" type="text/css" href="styles.css"/>
    <style>
        .myDropzone .dz-default.dz-message {

            background-image: url("<?php echo $this->baseUrl('/images/spritemap.png')?>") ;
    </style>
</head>

<body style=" -webkit-transform: translate3d(0, 0, 0)">
<div class="row user-page" style="background-color: #ffffff">
<?php
require_once(PUBLIC_PATH."/sidebar.php");
?>

    <div id="container" class="col-md-9" style="position: relative; top:5px;">
        <div>
            <img src="<?php echo $this->baseUrl('/images/upload-photos.jpg')?>" style="top: 15px; float: right; height: 60px; cursor: pointer;" onclick="toggleDroparea()" title="click to extend/minimize upload area">
        </div>

        <h3 class="title">Gallery</h3>

        <form id="deletephotos" action="<?php echo $this->baseUrl('/upload/delete-from-album') ?>">
            <button class="btn btn-danger" style="margin-bottom: 20px;position: relative;top:5px" title="Mark photos first for deletion" onclick="document.getElementById('deletephotos').submit()">Delete photos</button>
            <input type="hidden" id="photostodelete" name="photostodelete">

        <div id="album" class="album">

            <?php for( $i = 0; $i < count( $pictures ); $i++ ): ?>
                <div class="photoFrame">

                    <img id="<?php echo $pictures[$i] ?>"
                         src="<?php echo $this->baseUrl('/photos/gallery/thumb') . "/". $pictures[$i]?>"
                         alt="<?php echo $photopath ."/". $pictures[$i]?>" onclick="mark(this,<?php echo $i ?>)" >

                </div>
            <?php endfor ?>

        </div>
       </form>


        <div class="myDropzone" id="dropareaphoto"  title="Click or drag here to add picture" >
            <div class="ta-right">
                <button id="closebutton" class="btn btn-danger" >Close</button>
                <button id="resetbutton" class="btn btn-danger" >Reset</button>
                <button id="uploadbutton" class="btn btn-primary">Upload photos</button>
            </div>

            <div id="uploadarea" >
                <form action="<?php echo $this->baseUrl('/upload/photo') ?>" class="dropzone" id="my-dropzone" style="width: 800px; height: 750px">
                    <input type="hidden" id="realfiles" name="realfiles">
                    <input type="hidden" id="baseUrl" name="baseUrl" value="<?php echo $this->baseUrl('/images/remove1.png') ?>" >

<!--                    <input type="hidden" id="baseUrl" name="baseUrl" value="<?php /*echo rtrim($this->baseUrl('/'),'/')*/?>" >-->
                </form>
            </div>
            <div id="uploaddone"
                 style="display: none;background-color: greenyellow; text-align:center;border-radius: 40%;font-size: 10px;padding: 20px" >
            </div>
        </div>

    </div>

</div>


</body>


<script type="text/javascript">

var dropArea = $("#dropareaphoto");

var photos=[];
var photolist=[];


if ($(window).width() <= 1200) {
    $("#album").width(700);

}
else
{
    $("#album").width(850);

}

function toggleDroparea(){

    dropArea.slideToggle(function(){
        if( ! dropArea.is(':visible') ){
             location.reload(true);
        }

    });

}

function hideDroparea(){

    dropArea.slideUp(function(){
        if( ! dropArea.is(':visible') ){
            location.reload(true);
        }

    });

}

$("#closebutton").click(function(){
    hideDroparea();
});

$(window).on('resize', function(){
    var win = $(this); //this = window
    if (win.height() >= 820) { /* ... */ }
    if (win.width() <= 1200) {
        $("#album").width(700);
    }
    else
    {
        $("#album").width(850);

    }

});


function mark(elem,i){
    if (photos[i]==null)
        photos[i]=0;

    if (photos[i]==0)
    {
        elem.style.opacity = "0.6";
        elem.style.filter  = 'alpha(opacity=60)';
        photos[i]=1;  //marked for delete
        photolist.push(elem.id);
    }
    else
    {
        elem.style.opacity = "1";
        elem.style.filter  = 'alpha(opacity=100)';
        photos[i]=0;
        photolist.splice(elem.id,1);
    }

    $("#photostodelete").val(JSON.stringify(photolist));

}



</script>
