
<?php
//left sidebar for admins

$act = $this->action;
$this->placeholder('sidebar')->captureStart() ?>
<div class="col-md-3 m-menu">
    <h3>Users</h3>
    <ul class="nav nav-pills nav-stacked">
        <li <?php echo $act == 'index' ? 'class="active"':''?>><a href="/user">Users list</a></li>
        <li <?php echo $act == 'add' ? 'class="active"':''?>><a href="/user/add">Registrate user</a></li>
        <li <?php echo $act == 'edit' ? 'class="active"':''?>><a href="/user/edit?id=<?php echo $this->identity['id'] ?>">Profile</a></li>
        <li <?php echo $act == 'photos' ? 'class="active"':''?>><a href="/user/photos">Photos</a></li>
        <li <?php echo $act == 'gallery' ? 'class="active"':''?>><a href="/upload/gallery">Gallery</a></li>
    </ul>
</div>
<?php $this->placeholder('sidebar')->captureEnd()  ?>