
<?php $act = $this->action ?>
<?php $this->placeholder('signinbar')->captureStart() ?>

<!--        bara sign in    -->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-right" method="post">
                <div class="form-group">
                    <input type="email" name="signed_email" placeholder="Email" class="form-control">
                </div>
                <div class="form-group">
                    <input type="password" name="signed_password" placeholder="Password" class="form-control">
                </div>
                <button type="submit" class="btn btn-success">Sign in</button>
            </form>
        </div><!--/.navbar-collapse -->


<?php $this->placeholder('signinbar')->captureEnd()  ?>