<?php

    $this->headScript()
        ->appendFile($this->baseUrl('/js/dropzone.js'))
        ->appendFile($this->baseUrl('/js/upload-avatar.js'));

?>
<div class="row user-page" style="background-color: #ffffff">

    <!--Include Meniu -->
    <?php echo $this->placeholder('sidebar') ?>

    <div class="col-md-9">
        <h3 class="title">New user registration</h3>

        <form id="jsAddUser" class="form-horizontal" role="form" method="post" action="" autocomplete="off">

            <div class="form-group">
                <label for="inputUsername" class="col-sm-3 control-label">UserName*</label>
                <div class="col-sm-4">
                    <input id="inputUsername" type="text" class="form-control required"
                           placeholder="Username" name="username" value="">
                </div>
            </div>

            <div class="form-group">
                <label for="inputEmail" class="col-sm-3 control-label">Email*</label>
                <div class="col-sm-4">
                    <input  id="inputEmail" type="email" class="form-control required email"
                            placeholder="Email" name="email">
                </div>
            </div>

            <div class="form-group">
                <label for="inputPassword" class="col-sm-3 control-label">Password*</label>
                <div class="col-sm-4">
                    <input id="inputPassword" type="password" class="form-control required"
                           placeholder="Password" name="password">
                </div>
            </div>

            <div class="form-group">
                <label for="inputPassword2" class="col-sm-3 control-label">Retype Password*</label>
                <div class="col-sm-4">
                    <input id="inputPassword2" type="password" class="form-control required"
                           placeholder="Retype Password" name="password2">
                </div>
            </div>


            <div class="form-group">
                <label for="inputFirstName" class="col-sm-3 control-label">First Name*</label>
                <div class="col-sm-4">
                    <input id="inputFirstName" type="text" class="form-control required"
                           placeholder="Firstname" name="first_name">
                </div>
            </div>

            <div class="form-group">
                <label for="inputLastName" class="col-sm-3 control-label">Last Name*</label>
                <div class="col-sm-4">
                    <input id="inputLastName" type="text" class="form-control required"
                           placeholder="Lastname" name="last_name">
                </div>
            </div>
            
            <div class="form-group">
                <label for="inputPhone" class="col-sm-3 control-label">Phone</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" id="inputPhone" placeholder="Phone" name="phone">
                </div>
            </div>

            <div class="form-group">
                <label for="inputRole" class="col-sm-3 control-label">Role</label>
                <div class="col-sm-4">
                    <select id="inputRole" name="role">
                        <option value="<?php echo  Table_User::ROLE_ADMIN ?>"><?php echo  Table_User::ROLE_ADMIN ?></option>
                        <option value="<?php echo  Table_User::ROLE_USER ?>"><?php echo  Table_User::ROLE_USER ?></option>

                    </select>

                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-9">
                    <button type="submit" name="adduser" class="btn btn-primary">Add user</button>
                </div>
            </div>
            <input type="hidden" id="photoup" name="photoup" >
        </form>
        <div class="myDropzone" id="droparea" title="Click or drag here to add picture" >
        <form action="<?php echo $this->baseUrl('/upload') ?>" class="dropzone" id="my-dropzone">

               <img src="/images/add-user.jpg" id="imagebutton" class="col-sm-offset-3" width="100px" onclick="$('#my-dropzone').submit()">
                <img src="/images/remove1.png" title="click to remove picture" id="buttonremove" class="picremove">
            </form>

        </div>

    </div>
</div>

<script type="text/javascript">

$("input").change(function(){
    var test= $('#inputUsername').val();
    test = test.toLowerCase();
    $('#inputUsername').val(test);


    test= $('#inputEmail').val();
    test = test.toLowerCase();
    $('#inputEmail').val(test);

});

    $(function(){
    $('#jsAddUser').validate({
        rules: {
            username: {
                minlength: 4,
                remote: "/auth/check-username"
            },
            email: {
                remote: "/auth/check-email"
            },
            password: {
                minlength: 4
            },
            password2: {
                equalTo: "#inputPassword"
            }
        }
    });
})


</script>
