<?php
    $this->headScript()->appendFile("http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js");

    /** @var Model_User $user */
    $user = $this->user;
?>
<div class="row user-page">

    <!--Include Meniu -->
    <?php echo $this->placeholder('sidebar') ?>

    <div class="col-md-9">
        <h3 class="title">Editare utilizator</h3>

        <form id="jsAddUser" class="form-horizontal" role="form" method="post" action="" autocomplete="off">

            <div class="form-group">
                <label for="inputUsername" class="col-sm-3 control-label">UserName*</label>
                <div class="col-sm-4">
                    <input id="inputUsername" type="text" class="form-control required"
                           placeholder="username" name="username" value="<?php echo $user->getUsername()?>">
                </div>
            </div>

            <div class="form-group">
                <label for="inputEmail" class="col-sm-3 control-label">Email*</label>
                <div class="col-sm-4">
                    <input  id="inputEmail" type="email" class="form-control required email"
                            placeholder="Email" name="email" value="<?php echo $user->getEmail() ?>">
                </div>
            </div>

            <div class="form-group">
                <label for="inputPassword" class="col-sm-3 control-label">Password*</label>
                <div class="col-sm-4">
                    <input id="inputPassword" type="password" class="form-control"
                           placeholder="Password" name="password">
                </div>
            </div>

            <div class="form-group">
                <label for="inputPassword2" class="col-sm-3 control-label">Retype Password*</label>
                <div class="col-sm-4">
                    <input id="inputPassword2" type="password" class="form-control"
                           placeholder="Retype Password" name="password2">
                </div>
            </div>


            <div class="form-group">
                <label for="inputFirstName" class="col-sm-3 control-label">First Name*</label>
                <div class="col-sm-4">
                    <input id="inputFirstName" type="text" class="form-control required"
                           placeholder="firstname" name="first_name" value="<?php echo $user->getFirstName()?>">
                </div>
            </div>

            <div class="form-group">
                <label for="inputLastName" class="col-sm-3 control-label">Last Name*</label>
                <div class="col-sm-4">
                    <input id="inputLastName" type="text" class="form-control required"
                           placeholder="lastname" name="last_name" value="<?php echo $user->getLastName()?>">
                </div>
            </div>

            <div class="form-group">
                <label for="inputPhone" class="col-sm-3 control-label">Phone</label>
                <div class="col-sm-4">
                    <input id="inputPhone" type="text" class="form-control"
                           placeholder="phone" name="phone" value="<?php echo $user->getPhone()?>">
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-9">
                    <button type="submit" name="adduser" value="Adaugare" class="btn btn-primary">Adaugare</button>
                </div>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
    $(function(){
        $('#jsAddUser').validate({
            rules: {
                username: {
                    minlength: 4
                },
                email: {
                    remote: "/user/check-email"
                },
                password: {
                    minlength: 4
                },
                password2: {
                    equalTo: "#inputPassword"
                }
            }
        });
    })
</script>
