<div class="row min-height">
    <?php echo $this->placeholder('sidebar') ?>

    <div class="col-md-9">
        <h3>Adaugare utilizator nou</h3>


        <form class="form-horizontal" role="form" method="post" action="" autocomplete="off">
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
                <div class="col-sm-4">
                    <input type="email" class="form-control" id="inputEmail3" placeholder="Email" name="email">
                </div>
            </div>
            <div class="form-group">
                <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
                <div class="col-sm-4">
                    <input type="password" class="form-control" id="inputPassword3" placeholder="Password" name="password">
                </div>
            </div>
            <div class="form-group">
                <label for="inputNume" class="col-sm-2 control-label">Nume</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" id="inputNume" placeholder="Nume" name="password">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-4">
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="rememberMe" value="1"> Remember me
                        </label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary">Adaugare</button>
                </div>
            </div>
        </form>
    </div>

</div>