<?php
$this->headScript()->appendFile($this->baseUrl('/js/jquery.validate.min.js'))
    ->appendFile($this->baseUrl('/js/dropzone.js'))
    ->appendFile($this->baseUrl('/js/upload-photo.js'));

    /** @var Model_User $user */

    $user = $this->user;

?>

<body onload="setRole()">
<div class="row user-page" style="background-color: #ffffff">

    <!--Include Meniu -->
    <?php echo $this->placeholder('sidebar') ?>

    <div class="col-md-9">
        <h3 class="title">Edit user profile</h3>

        <form id="jsEditUser" class="form-horizontal" role="form" method="post" action="" autocomplete="off" >
            <input type="hidden" id="getRole" value="<?php echo $user->getRole() ?>">
            <input id="id" name="id" type="hidden" value="<?php echo $user->getId() ?>">

            <div class="form-group">
                <label for="inputUsername" class="col-sm-3 control-label">UserName*</label>
                <div class="col-sm-4">
                    <input id="inputUsername" type="text" class="form-control required"
                           placeholder="Username" name="username" value="<?php echo $user->getUsername()?>" >
                </div>
            </div>

            <div class="form-group">
                <label for="inputEmail" class="col-sm-3 control-label">Email*</label>
                <div class="col-sm-4">
                    <input  id="inputEmail" type="email" class="form-control required"
                            placeholder="Email" name="email" value="<?php echo $user->getEmail() ?>">
                </div>
            </div>

            <div class="form-group">
                <label for="inputPassword" class="col-sm-3 control-label">Password</label>
                <div class="col-sm-4">
                    <input id="inputPassword" type="password" class="form-control"
                           placeholder="Password" name="password">
                </div>
            </div>

            <div class="form-group">
                <label for="inputPassword2" class="col-sm-3 control-label">Retype Password</label>
                <div class="col-sm-4">
                    <input id="inputPassword2" type="password" class="form-control"
                           placeholder="Retype Password" name="password2">
                </div>
            </div>


            <div class="form-group">
                <label for="inputFirstName" class="col-sm-3 control-label">First Name*</label>
                <div class="col-sm-4">
                    <input id="inputFirstName" type="text" class="form-control required"
                           placeholder="Firstname" name="first_name" value="<?php echo $user->getFirstName()?>">
                </div>
            </div>

            <div class="form-group">
                <label for="inputLastName" class="col-sm-3 control-label">Last Name*</label>
                <div class="col-sm-4">
                    <input id="inputLastName" type="text" class="form-control required"
                           placeholder="Lastname" name="last_name" value="<?php echo $user->getLastName()?>">
                </div>
            </div>

            <div class="form-group">
                <label for="inputPhone" class="col-sm-3 control-label">Phone</label>
                <div class="col-sm-4">
                    <input id="inputPhone" type="text" class="form-control"
                           placeholder="Phone" name="phone" value="<?php echo $user->getPhone()?>">
                </div>
            </div>

            <div class="form-group">
                <label for="inputRole" class="col-sm-3 control-label">Role</label>
                <div class="col-sm-4">
                    <select id="inputRole" name="role">
                        <option value="<?php echo  Table_User::ROLE_ADMIN ?>"><?php echo  Table_User::ROLE_ADMIN ?></option>
                        <option value="<?php echo  Table_User::ROLE_USER ?>"><?php echo  Table_User::ROLE_USER ?></option>

                    </select>

                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-9">
                    <input type="submit" name="edituser" value="Save profile" class="btn btn-primary" >
                </div>
            </div>
            <input type="hidden" id="photoup" name="photoup" >

        </form>
        <div class="myDropzone" id="droparea" title="Click or drag here to add picture" >
            <form action="<?php echo $this->baseUrl('/upload') ?>" class="dropzone" id="my-dropzone">
                <input id="idphoto" name="idphoto" type="hidden" value="<?php echo $user->getId() ?>">
                <img src="/images/add-user.jpg"  id="imagebutton" class="col-sm-offset-3" width="100px" onclick="$('#my-dropzone').submit()">
                <img src="/images/remove1.png" title="click to remove picture" id="buttonremove" class="picremove">
            </form>

        </div>
    </div>
</div>


<script type="text/javascript">
    $("input").change(function(){
        var test= $('#inputUsername').val();
        test = test.toLowerCase();
        $('#inputUsername').val(test);


        test= $('#inputEmail').val();
        test = test.toLowerCase();
        $('#inputEmail').val(test);

    });

    $(function(){

        $('#jsEditUser').validate({
            rules: {
                username: {
                    minlength: 4,
                    remote: {url:"/auth/check-username",
                             type:"post",
                             data: {
                                id: function() {
                                    return $("#id").val();
                                }
                            }
                         }
                },
                email: {
                    remote: {url:"/auth/check-email",
                             type:"post",
                        data: {
                            id: function() {
                                return $("#id").val();
                            }
                        }
                    }
                },
                password: {
                    minlength: 4
                },
                password2: {
                    equalTo: "#inputPassword"
                }
            }
        });
    })

    function setRole()
    {
        role=$("#getRole").val();
        $("#inputRole").val(role);
    }

</script>
</body>