<div class="row min-height">


    <!-- Include menu  -->
    <?php echo $this->placeholder('sidebar') ?>

    <div class="col-md-9">
        <h3>Lista inregistrari</h3>
        <form method="post" >
            <table class="table table-bordered table-striped table-hover table-condensed">
                <thead>
                <tr>
                    <td><input id="all" type="checkbox"></td>
                    <td>#</td>
                    <td>UserName</td>
                    <td>FullName</td>
                    <td>Email</td>
                    <td>Phone</td>
                </tr>
                </thead>
                <tbody>
                <?php
                    $i = 0;
                    /**@var Model_User $user */
                  //  Zend_Debug::dump($this->users);
                    foreach( $this->users as $user) :

                      $i += 1;
                    ?>
                <tr>
                    <td><input type="checkbox" name="cb[]" value="<?php echo $user->getId()?>"></td>
                    <td><?php echo $i ?></td>
                    <td><?php echo $user->getUsername()?></td>
                    <td><?php echo $user->getFullName()?></td>
                    <td><?php echo $user->getEmail()?></td>
                    <td><?php echo $user->getPhone()?></td>
                </tr>
                <?php endforeach ?>
                </tbody>
            </table>
            <input type="submit" value="Delete" class="btn btn-danger">
        </form>
    </div>


</div>