<?php
class MenuClass
{
    static protected $_instance;
    static protected $selection=1;

    public function __construct(){

    }
    public function setSelection($selection)
    {
        self::$selection = $selection;
        return self::$selection;
    }

    public function getSelection()
    {
        return self::$selection;
    }

    static public function getInstance(){
    if( is_null( self::$_instance) ){
  //      print "Instanta Noua !\n";
        self::$_instance = new MenuClass();
    }
    return self::$_instance;

    }

    public function ShowMenu($selection){
    MenuClass::setSelection($selection);
    echo '
        <div class="col-md-3 m-menu">
        <h3>Utilizatori</h3>
        <ul class="nav nav-pills nav-stacked">';

        $sel1="";
        $sel2="";
        $sel3="";
        switch (self::$selection){
            case self::$selection=1:
                $sel1="active";
                break;
            case self::$selection=2:
                $sel2="active";
                break;
            case self::$selection=3:
                $sel3="active";
                break;

        }

        echo'
            <li class="'.$sel1.'"><a href="#">Lista</a></li>
            <li class="'.$sel2.'"><a href="/user/add">Adaugare</a></li>
            <li class="'.$sel3.'"><a href="">Stergere</a></li>
        </ul>
    </div>

    ';



    }
}
?>

<div class="row min-height">

<?php
$menu=MenuClass::getInstance();
$menu->ShowMenu(1);
//echo $menu->getSelection();

?>
<!--
    <div class="col-md-3 m-menu">
        <h3>Utilizatori</h3>
        <ul class="nav nav-pills nav-stacked">
            <li class="active"><a href="#">Lista</a></li>
            <li><a href="/user/add">Adaugare</a></li>
            <li><a href="">Stergere</a></li>
        </ul>
    </div>
   -->
    <div class="col-md-9">
        <h3>Lista</h3>

        <table class="table table-bordered table-striped table-hover table-condensed">
            <thead>
            <tr>
                <td>#</td>
                <td>Nume</td>
                <td>Email</td>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>1</td>
                <td>Sergiu Neamt</td>
                <td>nnsese@gmail.com</td>
            </tr>
            </tbody>
        </table>
    </div>

</div>
