
<div class="row user-page" style="background-color: #ffffff">


    <!-- Include menu  -->
    <?php echo $this->placeholder('sidebar') ?>

    <div class="col-md-9" >
        <h3 class="title">Lista inregistrari</h3>
        <form method="post" >
            <table id="myTable" class="table table-bordered table-striped table-hover table-condensed">
                <thead>
                <tr>
                    <td class="text-center"><input id="all" type="checkbox" onchange="check_ids()"></td>
                    <td>#</td>
                    <td>UserName</td>
                    <td>FullName</td>
                    <td>Email</td>
                    <td>Phone</td>
                    <td>Role</td>
                </tr>
                </thead>
                <tbody>
                <?php

                    $i = 0;
                    /**@var Model_User $user */
                  //  Zend_Debug::dump($this->users);
                    foreach( $this->users as $user) :
                        $i += 1;
                        $userId = $user->getId();
                ?>
                <!--se va trimite variabila $user la edit.phtml,pe rand fiecare inregistrare,se creaza linkuri cu transmiterea id-->
                <tr class="jsEdit" data-user-id="<?php echo $userId ?>" title="Click to Edit">
                    <td class="text-center"><input type="checkbox" name="cb[]" id="<?php echo 'crt'.$i ?>" value="<?php echo $userId?>" ></td>
                    <td class="text-center"><?php echo $i ?></td>
                    <td><?php echo $user->getUsername()?></td>
                    <td><?php echo $user->getFullName()?></td>
                    <td><?php echo $user->getEmail()?></td>
                    <td><?php echo $user->getPhone()?></td>
                    <td><?php echo $user->getRole()?></td>
                </tr>
                <?php endforeach ?>
                </tbody>
            </table>
            <input type="submit" value="Sterge" class="btn btn-danger">
        </form>
    </div>

</div>
<script type="text/javascript">
    function check_ids()
    {
       i=1;
       if ($("#all").prop('checked'))
          while($("#crt"+i).length!=0)
        {
            $("#crt"+i).attr('checked', true);
            i++;
        }
       else
           while($("#crt"+i).length!=0)
           {
               $("#crt"+i).attr('checked', false);
               i++;
           }
    }

    $('#myTable').on('click','.jsEdit',function(event){
        var clicked = $(event.target).text();
        if (clicked!=Number(clicked))
        {
            location.href = '/user/edit?id=' + $(this).data("userId");
        }
    })

</script>