<?php
$act = $this->action ;
$name= $this->name;
//My_Log_Me::Log($this);

$this->placeholder('anyuserbar')->captureStart() ?>
<div class="col-md-3 m-menu">
    <h3><?php echo $name ?></h3>
    <ul class="nav nav-pills nav-stacked">
        <li <?php echo $act == 'index' ? 'class="active"':''?>><a href="/anyuser/profil">Profil</a></li>

    </ul>
</div>
<?php $this->placeholder('anyuserbar')->captureEnd()  ?>